name: meanflow
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - pytorch-cuda
  - matplotlib
  - jupyter
  - numpy
  - pip
  - pip:
    - ipykernel
    - torchmetrics[image]
    - torchvision
    - tensorboard

